### ISSUE TITLE
Seal all traits except `ObjectBehavior`

### ISSUE THREAD

**Issue by janhohenheim** [myelin-ai/engine#75]
ATM adding a new function to e.g. `Simulation` is a breaking change, as a consumer could have implemented it. We currently simply sweep this under the rug and mark it as a minor change.

**Comment by janhohenheim** [comment]
Blocked by https://github.com/myelin-ai/mockiato/issues/94

**Comment by tautropfli** [comment]
No longer blocked as myelin-ai/mockiato#94 has been closed.
